---
title: "Exploration"
author: "Ryan Steed"
output: html_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r deps}
source("R/utils.R")
```

# Explaining disparities
Why do racial groups have different outcomes? Two possible explanations: distance from eligibility thresholds, and differences in natural variance.

## Distances from eligibility thresholds
```{r}
experiment = load_experiment("baseline", 1) %>% mutate(not_hispanic = not_hispanic_or_latino_hispanic_or_latino_and_race_pct)
experiment
```
```{r}
thresholds = data.frame(raw=c(10, 6500, 10), prop=c(0.02, 0.15, 0.05), grant=c("Basic", "Concentration", "Targeted"))

point_plot = ggrastr::rasterise(geom_point(alpha=0.3, size=0.25, color="#3a3b3c"), dpi=100)
formatting = list(
  geom_smooth(method="lm", linetype="dashed", color="red"),
  theme(
    legend.position = "bottom",
    legend.box="vertical"
  ),
  scale_color_brewer(palette="Dark2"),
  guides(
    color=guide_legend("Eligibility Threshold")
  )
)

ggplot(experiment, aes(x=prop_white, y=ifelse(true_children_eligible == 0, 0, log(true_children_eligible)))) +
  point_plot +
  geom_hline(data=thresholds, aes(yintercept=log(raw), color=grant)) +
  formatting +
  labs(
    y="Log # of children in poverty",
    x="% white-only"
  )
ggsave("plots/race/thresholds_raw.pdf", dpi=300, width=6, height=5)

ggplot(experiment, aes(x=prop_white, y=log(true_children_eligible/true_children_total))) +
  point_plot +
  geom_hline(data=thresholds, aes(yintercept=log(prop), color=grant)) +
  formatting +
  labs(
    y="Log prop. of children in poverty",
    x="% white-only"
  )
ggsave("plots/race/thresholds_prop.pdf", dpi=300, width=6, height=5)

ggplot(experiment, aes(x=not_hispanic, y=ifelse(true_children_eligible == 0, 0, log(true_children_eligible)))) +
  point_plot +
  geom_hline(data=thresholds, aes(yintercept=log(raw), color=grant)) +
  formatting +
  labs(
    y="Log # of children in poverty",
    x="% non-Hispanic"
  )
ggsave("plots/race/thresholds_raw_ethnicity.pdf", dpi=300, width=6, height=5)

ggplot(experiment, aes(x=not_hispanic, y=log(true_children_eligible/true_children_total))) +
  point_plot +
  geom_hline(data=thresholds, aes(yintercept=log(prop), color=grant)) +
  formatting +
  labs(
    y="Log prop. of children in poverty",
    x="% non-Hispanic"
  )
ggsave("plots/race/thresholds_prop_ethnicity.pdf", dpi=300, width=6, height=5)
```

## Differences in natural variance
```{r}
ggplot(experiment, aes(x=prop_white, y=log(true_pop_total))) +
  geom_point(alpha=0.5, size=0.25) +
  geom_smooth(method="lm", linetype="dashed", color="red")
  # guides(
  #   color=guide_legend("Eligibility Threshold")
  # ) +
  labs(
    y="Log population",
    x="% white-only"
  )
```

# Robustness check: ACS-derived variability in race-weighted misallocation
```{r}
experiment = load_experiment("baseline", 1000)
comparison = readRDS("results/policy_experiments/baseline_comparison_trials=1000.rds")
comparison
```

```{r}
# Expected standard deviation, based on MOEs
stdev <- function(race_pct, race_pctmoe, name) {
  # Assuming we use nation-wide # of children for the denominator (low error),
  # then the std dev of the numerator is as follows:
  sse <- sum((experiment$misalloc_sampling * race_pctmoe / 1.645)**2)
  # divide by the denominator to get the stdev of race-weighted misalloc:
  Sys.sleep(1)
  print(sprintf(
    "%s: %.2f",
    name,
    sqrt(sse) / sum(race_pct * experiment$true_children_total))
  )
  # sse_dp <- sum((experiment$misalloc_dp_sampling * race_pctmoe / 1.645)**2)
  # print(sqrt(sse_dp) / sum(race_pct * experiment$true_children_total))
}
stdev(
  experiment$black_or_african_american_race_pct,
  experiment$black_or_african_american_race_pctmoe,
  "Black"
)
stdev(
  experiment$white_race_pct,
  experiment$white_race_pctmoe,
  "White"
)
stdev(
  experiment$asian_race_pct,
  experiment$asian_race_pctmoe,
  "Asian"
)
stdev(
  experiment$chinese_race_pct,
  experiment$chinese_race_pctmoe,
  "Chinese"
)
stdev(
  experiment$filipino_race_pct,
  experiment$filipino_race_pctmoe
)
stdev(
  experiment$japanese_race_pct,
  experiment$japanese_race_pctmoe,
  "Japenese"
)
stdev(
  experiment$korean_race_pct,
  experiment$korean_race_pctmoe,
  "Korean"
)
stdev(
  experiment$vietnamese_race_pct,
  experiment$vietnamese_race_pctmoe,
  "Vietnamese"
)
stdev(
  experiment$other_asian_race_pct,
  experiment$other_asian_race_pctmoe,
  "Other asian"
)
stdev(
  experiment$some_other_race_race_pct,
  experiment$some_other_race_race_pctmoe,
  "Some other"
)
stdev(
  experiment$cherokee_tribal_grouping_race_pct,
  experiment$cherokee_tribal_grouping_race_pctmoe,
  "Cherokee"
)
stdev(
  experiment$chippewa_tribal_grouping_race_pct,
  experiment$chippewa_tribal_grouping_race_pctmoe,
  "Chippewa"
)
stdev(
  experiment$navajo_tribal_grouping_race_pct,
  experiment$navajo_tribal_grouping_race_pctmoe,
  "Navajo"
)
stdev(
  experiment$sioux_tribal_grouping_race_pct,
  experiment$sioux_tribal_grouping_race_pctmoe,
  "Sioux"
)
stdev(
  experiment$native_hawaiian_race_pct,
  experiment$native_hawaiian_race_pctmoe,
  "Hawaiian"
)
stdev(
  experiment$guamanian_or_chamorro_race_pct,
  experiment$guamanian_or_chamorro_race_pctmoe,
  "Guamanian or Chamorro"
)
stdev(
  experiment$samoan_race_pct,
  experiment$samoan_race_pctmoe,
  "Samoan"
)
```