---
title: "Regression Analysis"
author: "Ryan Steed"
date: "9/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r deps}
library(stargazer)
library(tidyverse)
library(ggpubr)
library(janitor)
library(mgcv)
library(lmtest)
library(mgcViz)
library(tidymv)
library(MASS)
library(cowplot)
library(grid)
library(gridExtra)
```

```{r load}
# raw = read.csv("results/discrimination.csv")
raw = read.csv("results/discrimination_laplace_eps=0.1.csv")
```
```{r income}
# mask = raw$Median.household.income..dollars...INCOME.AND.BENEFITS..IN.2019.INFLATION.ADJUSTED.DOLLARS.....est == '250,000+'
# sum(mask)
# gsub('[\\+]|[,]', '', as.character(raw$Median.household.income..dollars...INCOME.AND.BENEFITS..IN.2019.INFLATION.ADJUSTED.DOLLARS.....est))[mask]
# as.numeric(gsub('[\\+]|[,]', '', as.character(raw$Median.household.income..dollars...INCOME.AND.BENEFITS..IN.2019.INFLATION.ADJUSTED.DOLLARS.....est)))[mask]
```

```{r clean}
# use short df
# df = raw %>% filter(trial < 10)
df = raw %>%
  clean_names() %>%
  mutate_at(
    vars(matches("race_pct$")), list(`children`= ~(. / 100 * true_children_total))
  )
df = df %>%
  mutate(
    prop_white = white_race_pct / 100,
    nonwhite_children = true_children_total * prop_white,
    # misalloc in terms of true grant total - TODO make sure this matches, normalize before this
    misalloc_dp = dp_grant_total - true_grant_total,
    misalloc_sampling = est_grant_total - true_grant_total,
    misalloc_dp_sampling = dpest_grant_total - true_grant_total,
    not_a_u_s_citizen_u_s_citizenship_status_pct = as.numeric(not_a_u_s_citizen_u_s_citizenship_status_pct),
    average_household_size_of_renter_occupied_unit_housing_tenure_est = as.numeric(gsub(',', '', average_household_size_of_renter_occupied_unit_housing_tenure_est)),
    median_income_est = as.numeric(gsub('[\\+]|[,]', '', as.character(median_household_income_dollars_income_and_benefits_in_2019_inflation_adjusted_dollars_est)))
  )
```

## Costs & benefits across groups
```{r average_across_trials}
grouped = df %>% 
  group_by(state_fips_code, district_id) %>%
  summarise(
    misalloc_dp = mean(misalloc_dp),
    misalloc_sampling = mean(misalloc_sampling),
    misalloc_dp_sampling = mean(misalloc_dp_sampling)
  ) %>%
  ungroup() %>%
  left_join(
    df %>% dplyr::select(
      state_fips_code, 
      district_id, 
      nonwhite_children,
      true_grant_total,
      true_pop_total,
      true_children_eligible,
      true_children_total, 
      prop_white,
      ends_with("race_pct"),
      language_other_than_english_language_spoken_at_home_pct,
      language_other_than_english_language_spoken_at_home_est,
      foreign_born_place_of_birth_est,
      foreign_born_place_of_birth_pct,
      not_a_u_s_citizen_u_s_citizenship_status_est,
      not_a_u_s_citizen_u_s_citizenship_status_pct,
      renter_occupied_housing_tenure_pct,
      renter_occupied_housing_tenure_est,
      average_household_size_of_renter_occupied_unit_housing_tenure_est,
      median_income_est
    ) %>% unique(),
    by=c("state_fips_code", "district_id")
  ) %>%
  mutate(
    misalloc_dp_per_child = misalloc_dp / true_children_total,
    misalloc_sampling_per_child = misalloc_sampling / true_children_total,
    misalloc_dp_sampling_per_child = misalloc_dp_sampling / true_children_total
  )
grouped

# optional - filter to only look at edge cases
# grouped = grouped  %>%
#   filter(
#     misalloc > mean(misalloc_per_child) + 2*sd(misalloc_per_child) | misalloc_per_child < mean(misalloc_per_child) - 2*sd(misalloc_per_child)
#   )
```

```{r results}
# misalloc per non-white student
ggplot(grouped, aes(x=prop_white)) +
  geom_point(aes(y=misalloc_sampling_per_child, color="Sampling"), alpha=0.5) +
  geom_point(aes(y=misalloc_dp_sampling_per_child, color="DP + Sampling"), alpha=0.5)
# average misalloc per student
ggplot(grouped) +
  geom_histogram(aes(x=misalloc_sampling_per_child, fill="Sampling"), bins=100, alpha=0.5) +
  geom_histogram(aes(x=misalloc_dp_sampling_per_child, fill="DP + Sampling"), bins=100, alpha=0.5)
# average misalloc per eligible student
ggplot(grouped) +
  geom_histogram(aes(x=misalloc_sampling / true_children_eligible, fill="Sampling"), bins=100, alpha=0.5) +
  geom_histogram(aes(x=misalloc_dp_sampling / true_children_eligible, fill="DP + Sampling"), bins=100, alpha=0.5)
```

```{r race}
# kind = "hispanic"
kind = "race_aggregate"
# kind = "race"
# kind = "intersectional"

comparison = grouped

if (kind == "hispanic") {
  comparison = comparison %>%
    dplyr::select(ends_with("hispanic_or_latino_and_race_pct") | !ends_with("race_pct"))
} else if (kind == "race_aggregate") {
  comparison = comparison %>%
    mutate(
      white_agg_race_pct = white_race_pct,
      black_or_african_american_agg_race_pct = black_or_african_american_race_pct,
      tribal_grouping_agg_race_pct = rowSums(across(ends_with("tribal_grouping_race_pct"))),
      asian_agg_race_pct = asian_race_pct,
      pacific_islander_agg_race_pct = rowSums(across(c(
        "native_hawaiian_race_pct",
        "guamanian_or_chamorro_race_pct",
        "samoan_race_pct"
      ))),
      some_other_race_agg_race_pct = some_other_race_race_pct,
      two_or_more_races_agg_race_pct = two_or_more_races_race_pct
    ) %>%
    dplyr::select(ends_with("agg_race_pct") | !ends_with("race_pct"))
} else {
  comparison = comparison %>%
    dplyr::select(!ends_with("hispanic_or_latino_and_race_pct")) %>%
    dplyr::select(
      !asian_race_pct
    )
}

remainder = comparison %>%
  dplyr::select(ends_with("race_pct")) %>%
  mutate(sum = rowSums(across(everything())))

# per the census, should add to 100 - https://www.census.gov/quickfacts/fact/note/US/RHI625219
print(remainder %>% filter(sum > 105.0))

# total misalloc per student ("burden")
comparison = comparison %>%
  # mutate(other_race_pct = 100-rowSums(across(ends_with("race_pct")))) %>%
  # mutate(other_race_pct = if_else(other_race_pct < 0, 0, other_race_pct)) %>%
  pivot_longer(
    ends_with("race_pct"),
    values_to="race_pct",
    names_to="race"
  ) %>%
  mutate(
    race=recode_factor(
      str_replace(race, "_race_pct", ""),
      `sioux_tribal_grouping` = "Sioux Tribal Grouping",
      `sioux_tribal_grouping` = "Sioux tribal grouping",
      `chippewa_tribal_grouping` = "Chippewa tribal grouping",
      `navajo_tribal_grouping` = "Navajo tribal grouping",
      `cherokee_tribal_grouping` = "Cherokee tribal grouping",
      `guamanian_or_chamorro` = "Guamanian or Chamorro",
      `native_hawaiian` = "Native Hawaiian",
      `white` = "White",
      `samoan` = "Samoan",
      `two_or_more_races` = "Two or more races",
      `filipino` = "Filipino",
      `japanese` = "Japanese",
      `black_or_african_american` = "Black or African American",
      `other_asian` = "Other Asian",
      `some_other_race` = "Some other race",
      `korean` = "Korean",
      `vietnamese` = "Vietnamese",
      `asian_indian` = "Asian Indian",
      `chinese` = "Chinese"
    )
  )

cuberoot = function(x) {
  return(sign(x)*abs(x)^(1/3))
}

comparison = comparison %>%
  # assuming misallocation is spread evenly across children,
  mutate(
    benefit_dp = misalloc_dp_per_child / race_pct * 100,
    benefit_sampling = misalloc_sampling_per_child / race_pct * 100,
    benefit_dp_sampling = misalloc_dp_sampling_per_child / race_pct * 100
  )

comparison_all = comparison %>%
  group_by(race) %>%
  mutate(
    children_of_race = round(true_children_total * race_pct / 100),
    children_of_race_eligible = round(true_children_eligible * race_pct / 100),
    dp_benefit_per_child = sum(misalloc_dp * race_pct / 100) / sum(children_of_race),
    dp_benefit_per_child_eligible = sum(misalloc_dp * race_pct / 100) / sum(children_of_race_eligible),
    sampling_benefit_per_child = sum(misalloc_sampling * race_pct / 100) / sum(children_of_race),
    sampling_benefit_per_child_eligible = sum(misalloc_sampling * race_pct / 100) / sum(children_of_race_eligible),
    dp_sampling_benefit_per_child = sum(misalloc_dp_sampling * race_pct / 100) / sum(children_of_race),
    dp_sampling_benefit_per_child_eligible = sum(misalloc_dp_sampling * race_pct / 100) / sum(children_of_race_eligible)
  )  %>%
  ungroup()

# comparison_mean = comparison_all %>%
#   group_by(race) %>%
#   summarise(
#     dp_benefit_per_child = sum(misalloc_dp * race_pct / 100) / sum(children_of_race),
#     dp_benefit_per_child_eligible = sum(misalloc_dp * race_pct / 100) / sum(children_of_race_eligible),
#     sampling_benefit_per_child = sum(misalloc_sampling * race_pct / 100) / sum(children_of_race),
#     sampling_benefit_per_child_eligible = sum(misalloc_sampling * race_pct / 100) / sum(children_of_race_eligible),
#     dp_sampling_benefit_per_child = sum(misalloc_dp_sampling * race_pct / 100) / sum(children_of_race),
#     dp_sampling_benefit_per_child_eligible = sum(misalloc_dp_sampling * race_pct / 100) / sum(children_of_race_eligible)
#   )
```

```{r race-plots}
# hist = comparison_all %>%
#   dplyr::select(
#     children_of_race, 
#     race, 
#     misalloc_dp_per_child, 
#     dp_benefit_per_child,
#     misalloc_sampling_per_child, 
#     sampling_benefit_per_child,
#     misalloc_dp_sampling_per_child, 
#     dp_sampling_benefit_per_child
#   ) %>%
#   uncount(children_of_race)
# 
# plot = list(
#   ggtitle("Misallocation by Race"),
#   ylab("# children")
# )

# ggplot(
#   hist,
#   aes(x=cuberoot(misalloc_dp_per_child))
# ) + geom_vline(mapping=aes(xintercept=cuberoot(dp_benefit_per_child)), data=comparison_mean, color="red") +
#   geom_histogram(bins=100) +
#   facet_wrap(~race, ncol=3, scales="free_y") +
#   xlab("Misallocation per child (DP minus no DP, no sampling)")
# ggplot(
#   hist,
#   aes(x=cuberoot(misalloc_sampling_per_child))
# ) + geom_vline(mapping=aes(xintercept=cuberoot(sampling_benefit_per_child)), data=comparison_mean, color="red") +
#   xlab("Misallocation per child (Sampling minus true)")
# ggplot(
#   hist,
#   aes(x=cuberoot(misalloc_dp_sampling_per_child))
# ) + geom_vline(mapping=aes(xintercept=cuberoot(dp_sampling_benefit_per_child)), data=comparison_mean, color="red") +
#   xlab("Misallocation per child (DP + sampling minus true)")

# plot = list(
#   geom_boxplot(notch=TRUE),
#   coord_flip(),
#   ggtitle("Misallocation by Race"),
#   xlab("Census Race Category")
# )
# ggplot(hist, aes(x=reorder(race, dp_benefit_per_child), y=cuberoot(misalloc_dp_per_child))) +
#   plot +
#   ylab("Misallocation (DP minus true) per child (cube root)")
# ggplot(hist, aes(x=reorder(race, sampling_benefit_per_child), y=cuberoot(misalloc_sampling_per_child))) +
#   plot +
#   ylab("Misallocation (sampling minus true) per child (cube root)")
# ggplot(hist, aes(x=reorder(race, dp_sampling_benefit_per_child), y=cuberoot(misalloc_dp_sampling_per_child))) +
#   plot +
#   ylab("Misallocation (DP + sampling minus true) per child (cube root)")


# stacked_bar = comparison_all %>%
#   pivot_longer(c(sampling_benefit_per_child_eligible, dp_sampling_benefit_per_child_eligible), names_to="noise_added", values_to="benefit_per_child_eligible")
# 
# ggplot(stacked_bar, aes(x=reorder(race, benefit_per_child_eligible), y=benefit_per_child_eligible, fill=noise_added)) +
#   geom_bar(stat="identity", position="dodge") +
#   coord_flip() +
#   ylab("Race-weighted misallocation per eligible child")


plot = list(
  geom_col(aes(fill="Sampling error")),
  coord_flip(),
  # ggtitle("Race-weighted misallocation"),
  xlab("Census Race Category")
)

# ggplot(comparison_all, aes(x=reorder(race, dp_benefit_per_child_eligible), y=dp_benefit_per_child_eligible)) +
#   plot +
#   ylab("Race-weighted misallocation per eligible child (DP minus true)")
# ggsave("plots/misalloc_race_dp.png", dpi=300, width=5, height=8)

sorted = comparison_all %>%
  mutate(race = fct_reorder(race, sampling_benefit_per_child_eligible)) %>%
  distinct(race, sampling_benefit_per_child_eligible, dp_sampling_benefit_per_child_eligible)
print(sorted)
ggplot(sorted, aes(x=race, y=sampling_benefit_per_child_eligible)) +
  plot +
  ylab("Race-weighted misallocation per eligible child") +
  geom_crossbar(
    data=sorted, 
    aes(
      x=race, 
      y=dp_sampling_benefit_per_child_eligible, 
      ymin=dp_sampling_benefit_per_child_eligible, 
      ymax=dp_sampling_benefit_per_child_eligible,
      fill="Sampling + DP"
    ), 
    color="red"
  ) +
  labs(
    fill = "Noise added"
  ) +
  theme(
    legend.position = "top"
  )
ggsave(sprintf("plots/misalloc_%s.png", kind), dpi=300, width=5, height=8)

# ggplot(comparison_all, aes(x=reorder(race, dp_sampling_benefit_per_child_eligible), y=dp_sampling_benefit_per_child_eligible)) +
#   plot +
#   ylab("Race-weighted misallocation (DP + sampling minus no true) per eligible child")
# ggsave("plots/misalloc_race_dp_sampling.png", dpi=300, width=5, height=8)

# misalloc_nonwhite = df$misalloc * (1-df$prop_white)
# misalloc_white = df$misalloc * df$prop_white
# t.test(misalloc_white, misalloc_nonwhite)
```

```{r population}
income = ggplot(grouped, aes(x=log(true_pop_total), y=misalloc_per_child)) 
income + geom_point() +
  stat_cor(method="pearson") +
  xlab("Log population") +
  ylab("Misallocation per child")

income + geom_hex(bins=30)
```

```{r income}
income = ggplot(grouped, aes(x=median_income_est, y=misalloc_per_child)) 
income + geom_point() +
  stat_cor(method="pearson") +
  xlab("Median income") +
  ylab("Misallocation per child")
income + geom_hex(bins=30)
```

```{r language}
lang = ggplot(grouped, aes(x=language_other_than_english_language_spoken_at_home_pct/100, y=misalloc_per_child)) 
lang + geom_point() +
  stat_cor(method="pearson") +
  xlab("% language other than English spoken at home") +
  ylab("Misallocation per child")
lang + geom_hex(bins=30)
```

```{r foreign}
foreign = ggplot(grouped, aes(x=foreign_born_place_of_birth_pct/100, y=misalloc_per_child)) 
foreign + geom_point() +
  stat_cor(method="pearson")
foreign + geom_hex(bins=30)
```

```{r ctznshp}
ctznshp = ggplot(grouped, aes(x=not_a_u_s_citizen_u_s_citizenship_status_pct/100, y=misalloc_per_child)) 
ctznshp + geom_point() +
  stat_cor(method="pearson") +
  xlab("% not a U.S. citizen") +
  ylab("Misallocation per child")
ctznshp + geom_hex(bins=30)
```

```{r renters}
renters = ggplot(grouped, aes(x=renter_occupied_housing_tenure_pct/100, y=misalloc_per_child)) 
renters + geom_point() +
  stat_cor(method="pearson") +
  xlab("% renter-occupied housing") +
  ylab("Misallocation per child")
renters + geom_hex(bins=30)
```

```{r household_size}
household_size = ggplot(grouped, aes(x=average_household_size_of_renter_occupied_unit_housing_tenure_est, y=misalloc_per_child)) 
household_size + geom_point() +
  stat_cor(method="pearson")
household_size + geom_hex(bins=30)
```

```{r two-way}

grouped_extreme = grouped  %>%
  filter(
    misalloc > mean(misalloc_per_child) + 2*sd(misalloc_per_child) | misalloc_per_child < mean(misalloc_per_child) - 2*sd(misalloc_per_child)
  )

grouped_extreme$highlight = grouped_extreme$misalloc_per_child > mean(grouped_extreme$misalloc_per_child) + 2*sd(grouped_extreme$misalloc_per_child) |
  grouped_extreme$misalloc_per_child < mean(grouped_extreme$misalloc_per_child) - 2*sd(grouped_extreme$misalloc_per_child)

ggplot(grouped_extreme, aes(x=prop_white, y=log(true_pop_total), color=misalloc_per_child)) +
  geom_point(size=1) +
  geom_point(data=subset(grouped_extreme, highlight), mapping=aes(x=prop_white, y=log(true_pop_total), color=misalloc_per_child)) +
  scale_colour_gradient2()

ggplot(grouped_extreme, aes(x=median_income_est, y=log(true_pop_total), color=misalloc_per_child)) +
  geom_point(size=1) +
  geom_point(data=subset(grouped_extreme, highlight), mapping=aes(x=median_income_est, y=log(true_pop_total), color=misalloc_per_child)) +
  scale_colour_gradient2()

ggplot(grouped_extreme, aes(x=prop_white, y=foreign_born_place_of_birth_pct/100, color=misalloc_per_child)) +
  geom_point(size=1) +
  geom_point(data=subset(grouped_extreme, highlight), mapping=aes(x=prop_white, y=foreign_born_place_of_birth_pct/100, color=misalloc_per_child)) +
  scale_colour_gradient2()

ggplot(grouped_extreme, aes(x=language_other_than_english_language_spoken_at_home_pct, y=log(true_pop_total), color=misalloc_per_child)) +
  geom_point(size=1) +
  geom_point(data=subset(grouped_extreme, highlight), mapping=aes(x=language_other_than_english_language_spoken_at_home_pct, y=log(true_pop_total), color=misalloc_per_child)) +
  scale_colour_gradient2()
```
  

## Effect of race on misallocations
```{r regressions}
sq_share = function(x) {
  return((x/100)^2)
}

df_abbrv = df %>%
  mutate(
    hhi = sq_share(white_race_pct) +
      sq_share(black_or_african_american_race_pct) +
      sq_share(cherokee_tribal_grouping_race_pct) +
      sq_share(chippewa_tribal_grouping_race_pct) +
      sq_share(navajo_tribal_grouping_race_pct) +
      sq_share(sioux_tribal_grouping_race_pct) +
      sq_share(asian_indian_race_pct) +
      sq_share(chinese_race_pct) +
      sq_share(filipino_race_pct) +
      sq_share(japanese_race_pct) +
      sq_share(korean_race_pct) +
      sq_share(vietnamese_race_pct) +
      sq_share(other_asian_race_pct) +
      sq_share(native_hawaiian_race_pct) +
      sq_share(guamanian_or_chamorro_race_pct) +
      sq_share(samoan_race_pct) +
      sq_share(some_other_race_race_pct) +
      sq_share(two_or_more_races_race_pct),
    prop_hispanic = 1-not_hispanic_or_latino_hispanic_or_latino_and_race_pct/100
  ) %>%
  dplyr::select(
    -ends_with("hispanic_or_latino_and_race_pct"),
    -asian_race_pct
  ) %>%
  filter(trial < 10)

nrow(df_abbrv)
```
### OLS

```{r ols}
lm = lm(misalloc ~ white_race_pct + black_or_african_american_race_pct, data=df_abbrv)
lm_cov = lm(misalloc ~ white_race_pct + black_or_african_american_race_pct + true_children_total + true_children_poverty, data=filtered)
lm_cov2 = lm(
  misalloc ~ white_race_pct + black_or_african_american_race_pct + true_children_total + true_children_poverty +
      log(true_pop_total) +
      language_other_than_english_language_spoken_at_home_pct +
      foreign_born_place_of_birth_pct +
      not_a_u_s_citizen_u_s_citizenship_status_pct +
      renter_occupied_housing_tenure_pct +
      average_household_size_of_renter_occupied_unit_housing_tenure_est +
      median_income_est,
  data=df_abbrv
)
lm2 = lm(sqrt(misalloc^2) ~ white_race_pct + black_or_african_american_race_pct, data=df_abbrv)
lm2_cov = lm(sqrt(misalloc^2) ~ white_race_pct + black_or_african_american_race_pct + true_children_total + true_children_poverty, data=df_abbrv)
lm2_cov2 = lm(
  sqrt(misalloc^2) ~ white_race_pct + black_or_african_american_race_pct + true_children_total + true_children_poverty +
      log(true_pop_total) +
      language_other_than_english_language_spoken_at_home_pct +
      foreign_born_place_of_birth_pct +
      not_a_u_s_citizen_u_s_citizenship_status_pct +
      renter_occupied_housing_tenure_pct +
      average_household_size_of_renter_occupied_unit_housing_tenure_est +
      median_income_est, 
  data=df_abbrv
)

stargazer(
  lm, lm_cov, lm_cov2, lm2, lm2_cov, lm2_cov2,
  type="text",
  title="Correlation between covariates and DP-induced misallocation. Positive = more received under DP.",
  covariate.labels=c("Proportion White", "Proportion Black", "Proportion Asian", "Total # children", "Total # children in poverty", "Log population", "% language other than English spoken at home", "% foreign-born", "% not a U.S. citizen", "% Renters", "Avg. household size", "Median income"),
  label="discrimination",
  omit=c("trial", "district_id", "state_fips_code")
  # out="results/discrimination.tex"
)
```

### GAM
```{r gam}
# print(names(df_abbrv))

# min(df_abbrv$misalloc_per_child)

# ggplot(df_abbrv, aes(x=prop_white, y=misalloc_per_child)) +
#   geom_point(alpha=0.1) +
#   geom_smooth()

lm_fit = lm(misalloc ~ prop_white, data=df_abbrv)
lm_fit
gam_fit = gam(misalloc ~ s(prop_white, bs="cr"), data=df_abbrv)
gam_fit

anova(lm_fit, gam_fit)
```

```{r gam-mr}
sampling_only = TRUE

if (sampling_only) {
  df_abbrv = df_abbrv %>% mutate(misalloc = misalloc_sampling)
} else {
  df_abbrv = df_abbrv %>% mutate(misalloc = misalloc_dp_sampling)
}

lm_mr = lm(
  misalloc_sampling~ prop_white +
      true_children_total + 
      true_children_poverty +
      log(true_pop_total) +
      median_income_est +
      hhi +
      prop_hispanic +
      # not_a_u_s_citizen_u_s_citizenship_status_pct +
      renter_occupied_housing_tenure_pct +
      average_household_size_of_renter_occupied_unit_housing_tenure_est,
  data=df_abbrv
)
summary(lm_mr)

gam_mr = gam(
  misalloc_sampling ~ s(prop_white, bs="tp") +
      s(median_income_est, bs="tp") +
      s(true_children_total, bs="tp") +
      s(true_children_poverty, bs="tp") +
      s(log(true_pop_total), bs="tp") +
      s(hhi, bs="tp") +
      s(prop_hispanic, bs="tp") +
      # s(not_a_u_s_citizen_u_s_citizenship_status_pct, bs="tp") +
      s(renter_occupied_housing_tenure_pct, bs="tp") +
      s(average_household_size_of_renter_occupied_unit_housing_tenure_est, bs="tp"),
  method="REML", # restricted MLE
  data=df_abbrv
)
summary(gam_mr)

anova(lm_mr, gam_mr)
```

```{r gam-interact}
gam_mr_interact = gam(
  misalloc ~
      te(
        prop_white,
        hhi,
        median_income_est
      ) +
      s(true_children_total, bs="tp") +
      s(true_children_poverty, bs="tp") +
      s(log(true_pop_total), bs="tp") +
      s(prop_hispanic, bs="tp"),
      # ti(
      #   language_other_than_english_language_spoken_at_home_pct,
      #   foreign_born_place_of_birth_pct,
      #   not_a_u_s_citizen_u_s_citizenship_status_pct
      # ) +
      # ti(
      #   renter_occupied_housing_tenure_pct,
      #   average_household_size_of_renter_occupied_unit_housing_tenure_est
      # ),
  method="REML", # restricted MLE
  data=df_abbrv
)
summary(gam_mr_interact)
anova(gam_mr, gam_mr_interact)
```

```{r gam_viz}
# plot_smooths(
#   model=gam_fit,
#   series=prop_white
# )

# vis.gam(gam_mr, view=c("prop_white", "median_income_est"))

m = gam_mr
viz = getViz(m)
```
```{r gam_plots}

plt = plot(viz, select=1:9, ask=FALSE)


# print(summary(plt$plots[[1]]$ggObj))
# ggsave("plots/test.png", plt$plots[[1]]$ggObj)

# return()



labels = c(
  "% white-only",
  "Median income",
  "# children",
  "# children in poverty",
  "Log population",
  "Racial homogeneity (HHI)",
  "% hispanic",
  "% renter-occupied housing",
  "Average size of renter household"
)
plt = function(i) {
  p = plot(sm(viz, i)) +
    theme_minimal() +
    # ylab("Smoothed effect (in terms of $$ misallocated)") +
    l_ciPoly() +
    l_fitLine() +
    geom_hline(yintercept = 0, linetype = 2) +
    theme(
      axis.title.x = element_blank(),
      axis.title.y = element_blank()
    ) +
    ggtitle(labels[i])
  p$ggObj
}

cplt = cowplot::plot_grid(plotlist=map(1:9, plt), nrow=3)
y.grob = textGrob(
  "Smoothed effect (in terms of $$ misallocated)",
  gp=gpar(fontface="bold"),
  rot=90
)
plot = grid.arrange(arrangeGrob(cplt, left=y.grob))
if (sampling_only) {
  ggsave("plots/smooths_sampling.png", plot, width=12, height=6, dpi=300)
} else {
  ggsave("plots/smooths_dp_sampling.png", plot, width=12, height=6, dpi=300)
}

check(viz)

# plot_smooths(
#   model=m,
#   series=prop_white
# ) + formatting +
#   xlab("% white")
```

### Inverse welfare
```{r welfare-weights}
# ordinal_logit = polr(
#   misalloc ~ prop_white +
#       true_children_total + 
#       true_children_poverty +
#       log(true_pop_total) +
#       median_income_est +
#       hhi +
#       prop_hispanic,
#       # language_other_than_english_language_spoken_at_home_pct +
#       # foreign_born_place_of_birth_pct +
#       # not_a_u_s_citizen_u_s_citizenship_status_pct +
#       # renter_occupied_housing_tenure_pct +
#       # average_household_size_of_renter_occupied_unit_housing_tenure_est +
#   data=df_abbrv,
#   Hess=TRUE
# )
```


## Traditional discrimination analysis
```{r diff}
lm = lm(est_grant_total ~ true_grant_total + prop_white + trial + district_id + state_fips_code, data=df)

stargazer(
  lm,
  type="text",
  title="Correlation between race and estimated grant amount.",
  covariate.labels=c("True grant total", "Proportion white-only individuals"),
  label="discrimination"
  # out="results/discrimination.tex"
)
```

